### ISSUE TITLE
Footer is jacked up in IE11

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#13]
The website footer is positioned at the bottom of the viewport rather than the bottom of the site. It probably has something to do with the flexbox styles set on `#app`.

**Comment by Frewacom** [comment]
Tried it on my computer with IE11 and events and places won't load at all. Been waiting for a few minutes and still nothing.

**Comment by imacrayon** [comment]
Do you have the latest code? I just merged a fix for IE11 like an hour ago. The homepage should be making an AJAX request to `/api/events` to get the event data. If you don't have any events in the database that could be a problem too. Sorry, I haven't added any seed data for the database yet.

**Comment by Frewacom** [comment]
Sorry for the delayed response. I believe I were a bit unclear on my issue.
I navigated to your website https://eventsinwichita.com on my computer using IE11 and it didn't load any events, places, whatsoever. I did not it run in locally from my computer. 

I tried your website again a minute ago and the issue still persists on IE11. Events nor places are loading for me.

**Comment by imacrayon** [comment]
Oh I see, the live website lags behind this repo a little and the previous IE11 fixes had not been released yet. However, I just added those latest updates to the live site, so it *should* be working for you now, could you please check it one more time and let me know? Thanks!

**Comment by Frewacom** [comment]
Just tested it on IE11 and both events and places are loading as it should.
